export const CATEGORIES = [
  { slug: "reviews",         label: "Reviews",         icon: "⭐", match: (t: string) => /\b(review|reddit|honest|verdict|vs\b|comparison|alternative|pros.cons|worth it|overhyped|trustpilot|g2)\b/i.test(t) },
  { slug: "wix-acquisition", label: "Wix Acquisition", icon: "🤝", match: (t: string) => /\b(wix|acquisition)\b/i.test(t) },
  { slug: "how-to",          label: "How-To Guides",   icon: "🔧", match: (t: string) => /^(how to|step-by-step|build |create |set up|launch |deploy |configure |automate |integrate )/i.test(t) },
  { slug: "industry",        label: "Industry Guides", icon: "🏭", match: (t: string) => /\bfor (accounting|aerospace|agricult|architect|auto|aviation|banking|biotech|cannabis|chemical|construct|consult|consumer|crypto|cyber|defense|e-learning|elearning|energy|engineer|entertainment|environ|fashion|film|fintech|food|gaming|government|hospital|hr|insurance|legal|logistics|manufactur|media|mining|music|nonprofit|oil|pharma|photo|proptech|publish|real estate|recruit|retail|shipping|saas|sports|supply chain|telecom|transport|travel|wellness|wholesale)\b/i.test(t) },
  { slug: "professions",     label: "Professions",     icon: "👔", match: (t: string) => /\bfor (accountants|acupuncturist|actors|architects|artists|attorneys|bakers|barbers|bookkeeper|coaches|contractors|copywriter|dentists|designers|dog walker|electrician|event|financial|fitness|florist|freelan|graphic|hair|handyman|home inspector|hr manager|hvac|immigration|insurance|interior|it consult|jeweler|journalist|landscape|language tutor|life coach|locksmith|makeup|massage|mechanic|mediator|mental health|midwife|mortgage|music teacher|nail tech|notary|nutritionist|occupational|optometrist|orthodontist|painter|paralegal|personal chef|personal shopper|pet groom|physical|pilates|plumber|pr special|private invest|private tutor|property manager|psychologist|public speaker|real estate|recruiter|roofer|seo special|social worker|software engineer|speech|startup|stylist|surveyor|tax|therapist|title compan|tour guide|travel agent|ux designer|veterinarian|video editor|virtual assistant|web designer|wedding|yoga)\b/i.test(t) },
  { slug: "pricing",         label: "Pricing & ROI",   icon: "💰", match: (t: string) => /\b(pric|cost|roi|save|saving|worth|budget|cheap|free plan|subscription|revenue|monetiz|income|earn|charge|pay)\b/i.test(t) },
  { slug: "features",        label: "Features",        icon: "⚙️", match: (t: string) => /\b(authentication|database|api|webhook|permission|notification|search|report|dashboard|workflow|automation|file upload|email|sms|real-time|mobile|export|backup|audit|chart|visualization|pdf|payment|stripe|login|role)\b/i.test(t) },
  { slug: "getting-started", label: "Getting Started", icon: "🚀", match: (t: string) => /\b(beginner|tutorial|getting started|first app|quick start|complete guide|masterclass|introduction|overview|explained|plain english|what is)\b/i.test(t) },
  { slug: "comparisons",     label: "Comparisons",     icon: "⚖️", match: (t: string) => /\bvs\b|\bversus\b|alternative|switching from|replace /i.test(t) },
];

export type Category = typeof CATEGORIES[number];
